### ISSUE TITLE
Allow Customization of the Deck

### ISSUE THREAD

**Issue by timeracers** [SilasReinagel/GloomhavenPlayerAttackDeckTracker#1]
As characters gain perks or equip certain equipment the deck is modified, so customization is needed to represent that.

**Comment by SilasReinagel** [comment]
@timeracers This might be done. 

Try out the prototype at: http://gloomhavenplayerdeck.com

Now the App has a Setup Mode and a Play Mode. Later, I will add the advanced card types and/or elements.
